# Copyright 2021-2025 The OpenSSL Project Authors. All Rights Reserved.
#
# Licensed under the Apache License 2.0 (the "License").  You may not use
# this file except in compliance with the License.  You can obtain a copy
# in the file LICENSE in the source distribution or at
# https://www.openssl.org/source/license.html

name: Test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  linux-riscv64:
    runs-on: linux-riscv64
    steps:
    - uses: actions/checkout@v4
    - name: config
      run: ./config enable-fips enable-ec_nistp_64_gcc_128 enable-md2 enable-rc5 enable-ssl3 enable-ssl3-method enable-trace
    - name: config dump
      run: ./configdata.pm --dump
    - name: make
      run: make -j 8
    - name: get cpu info
      run: |
        cat /proc/cpuinfo
        ./util/opensslwrap.sh version -c
    - name: ZBA_ZBB_ZBC_ZBS_ZKT
      env:
        OPENSSL_riscvcap: ZBA_ZBB_ZBC_ZBS_ZKT
      run : |
        make test HARNESS_JOBS=${HARNESS_JOBS:-4}
