name: "Delete previews of merged PR"

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    if: github.event.pull_request.merged == true
    runs-on: "ubuntu-latest"
    steps:
      - name: "test"
        run: "echo $GITHUB_HEAD_REF"
      - name: "ls"
        run: "tree"
